<?php 
__( 'Calendars', 'wp-gcalendar' );
__( 'Add', 'wp-gcalendar' );
__( 'Name', 'wp-gcalendar' );
__( 'ID', 'wp-gcalendar' );
__( 'Language', 'wp-gcalendar' );
__( 'Mode', 'wp-gcalendar' );
__( 'Actions', 'wp-gcalendar' );
__( 'Are you sure you want to delete this calendar?', 'wp-gcalendar' );
__( 'Calendar', 'wp-gcalendar' );
__( 'Event', 'wp-gcalendar' );
__( 'Event Title', 'wp-gcalendar' );
__( 'Event date', 'wp-gcalendar' );
__( 'To', 'wp-gcalendar' );
__( 'Time', 'wp-gcalendar' );
__( 'Attendees', 'wp-gcalendar' );
__( 'PS: press enter to add an other email', 'wp-gcalendar' );
__( 'Notify me via', 'wp-gcalendar' );
__( 'before', 'wp-gcalendar' );
__( 'calendar ID', 'wp-gcalendar' );
__( 'Edit', 'wp-gcalendar' );
__( 'month', 'wp-gcalendar' );
__( 'week', 'wp-gcalendar' );
__( 'day', 'wp-gcalendar' );
__( 'Date', 'wp-gcalendar' );